{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.global.secretName }}
  labels:
    {{- include "integrador-chart.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
  target:
    name: {{ .Values.externalSecrets.targetSecretName | default (printf "%s-secrets" (include "integrador-chart.fullname" .)) }}
    creationPolicy: Owner
    template:
      metadata:
        labels:
          {{- include "integrador-chart.labels" . | nindent 8 }}
  data:
    - secretKey: postgres-password
      remoteRef:
        key: /integrador/prod/db/password # Reutiliza la misma clave que DB_PASSWORD
    - secretKey: password
      remoteRef:
        key: /integrador/prod/db/password # Reutiliza la misma clave que DB_PASSWORD
    - secretKey: replication-password
      remoteRef:
        key: /integrador/prod/db/replication-password
    - secretKey: DB_NAME
      remoteRef:
        key: /integrador/prod/db/name
    - secretKey: DB_USER
      remoteRef:
        key: /integrador/prod/db/username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /integrador/prod/db/password
    - secretKey: DB_HOST
      remoteRef:
        key: /integrador/prod/db/host
    - secretKey: DB_PORT
      remoteRef:
        key: /integrador/prod/db/port
    
{{- end }}